-- ============================================================
-- MATH Quest pet system migration 01
-- Creates the pet tables and indexes.
-- Run before: 20260705_02_pet_system_rls_triggers.sql
-- Safe to run more than once.
-- ============================================================

create table if not exists public.student_pets (
  student_id       text        primary key references public.students(id) on delete cascade,
  pet_id           text        not null,
  pet_name         text        not null default '',
  free_select_used integer     not null default 0 check (free_select_used between 0 and 3),
  rename_used      integer     not null default 0 check (rename_used between 0 and 3),
  selected_at      timestamptz not null default now(),
  updated_at       timestamptz not null default now()
);

create table if not exists public.student_pet_events (
  id            bigint      generated by default as identity primary key,
  student_id    text        not null references public.students(id) on delete cascade,
  event_type    text        not null check (event_type in ('select', 'rename', 'paid_change')),
  from_pet_id   text        default '',
  to_pet_id     text        default '',
  previous_name text        default '',
  new_name      text        default '',
  points_used   integer     not null default 0 check (points_used >= 0),
  created_at    timestamptz not null default now()
);

create index if not exists student_pet_events_student_id_idx
  on public.student_pet_events(student_id);

create index if not exists student_pet_events_created_idx
  on public.student_pet_events(created_at desc);
