-- Password reset request setup for MathQuest / checkrean
-- Run this once in Supabase SQL Editor before using the reset-password UI.

create table if not exists public.password_reset_requests (
  id           bigint      generated by default as identity primary key,
  student_id   text        not null references public.students(id) on delete cascade,
  student_name text        not null,
  grade        text        not null,
  reset_code   text        not null check (reset_code ~ '^[0-9]{6}$'),
  status       text        not null default 'pending'
                           check (status in ('pending', 'used', 'expired', 'cancelled')),
  created_at   timestamptz not null default now(),
  expires_at   timestamptz not null,
  used_at      timestamptz
);

create index if not exists password_reset_requests_student_id_idx
  on public.password_reset_requests(student_id);

create index if not exists password_reset_requests_status_expires_idx
  on public.password_reset_requests(status, expires_at);

create index if not exists password_reset_requests_created_idx
  on public.password_reset_requests(created_at desc);

-- Allow only one pending reset request per student.
-- The web app deletes expired pending rows before creating a new request.
create unique index if not exists password_reset_requests_one_pending_idx
  on public.password_reset_requests(student_id)
  where status = 'pending';

alter table public.password_reset_requests enable row level security;

drop policy if exists "password_reset_requests_public_all"
  on public.password_reset_requests;

create policy "password_reset_requests_public_all"
  on public.password_reset_requests
  for all
  to public
  using (true)
  with check (true);
