-- ============================================================
--  MATH Quest — ระบบเช็คชื่อนักเรียน
--  supabase_complete.sql  (รัน 1 ครั้งใน Supabase SQL Editor)
--  โรงเรียนกุงแก้ววิทยาคาร
-- ============================================================

-- ──────────────────────────────────────────────────────────
-- 0. Extensions
-- ──────────────────────────────────────────────────────────
create extension if not exists pgcrypto;

-- ──────────────────────────────────────────────────────────
-- 1. Tables
-- ──────────────────────────────────────────────────────────

create table if not exists public.students (
  id          text        primary key,
  name        text        not null,
  password    text        not null,
  grade       text        not null,
  role        text        not null default 'STUDENT'
                          check (role in ('STUDENT', 'TEACHER')),
  photo_url   text        default '',
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now()
);

create table if not exists public.attendance_logs (
  id          bigint      generated by default as identity primary key,
  timestamp   timestamptz not null default now(),
  student_id  text        not null references public.students(id) on delete cascade,
  status      text        not null check (status in ('มา', 'ขาด', 'ลา', 'กิจกรรม')),
  points      integer     not null default 0,
  session_id  text,
  created_at  timestamptz not null default now()
);

create table if not exists public.shop_items (
  item_id     text        primary key,
  item_name   text        not null,
  cost        integer     not null default 0 check (cost >= 0),
  description text        default '',
  image_url   text        default '',
  is_active   boolean     not null default true,
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now()
);

create table if not exists public.redemption_logs (
  id          bigint      generated by default as identity primary key,
  timestamp   timestamptz not null default now(),
  student_id  text        not null references public.students(id) on delete cascade,
  item_id     text        references public.shop_items(item_id) on delete set null,
  item_name   text        not null,
  points_used integer     not null default 0 check (points_used >= 0),
  status      text        not null default 'pending'
                          check (status in ('pending', 'approved', 'rejected')),
  created_at  timestamptz not null default now()
);

create table if not exists public.password_reset_requests (
  id           bigint      generated by default as identity primary key,
  student_id   text        not null references public.students(id) on delete cascade,
  student_name text        not null,
  grade        text        not null,
  reset_code   text        not null check (reset_code ~ '^[0-9]{6}$'),
  status       text        not null default 'pending'
                           check (status in ('pending', 'used', 'expired', 'cancelled')),
  created_at   timestamptz not null default now(),
  expires_at   timestamptz not null,
  used_at      timestamptz
);

create table if not exists public.system_settings (
  key         text        primary key,
  value       text        default '',
  updated_at  timestamptz not null default now()
);

-- ──────────────────────────────────────────────────────────
-- 2. Indexes
-- ──────────────────────────────────────────────────────────
create index if not exists attendance_logs_student_id_idx on public.attendance_logs(student_id);
create index if not exists attendance_logs_timestamp_idx  on public.attendance_logs(timestamp desc);
create index if not exists attendance_logs_session_id_idx on public.attendance_logs(session_id)
  where session_id is not null;
create index if not exists redemption_logs_student_id_idx on public.redemption_logs(student_id);
create index if not exists redemption_logs_timestamp_idx  on public.redemption_logs(timestamp desc);
create index if not exists redemption_logs_pending_timestamp_idx
  on public.redemption_logs(timestamp desc)
  where status = 'pending';
create index if not exists shop_items_is_active_idx       on public.shop_items(is_active);
create index if not exists password_reset_requests_student_id_idx
  on public.password_reset_requests(student_id);
create index if not exists password_reset_requests_status_expires_idx
  on public.password_reset_requests(status, expires_at);
create index if not exists password_reset_requests_created_idx
  on public.password_reset_requests(created_at desc);
create unique index if not exists password_reset_requests_one_pending_idx
  on public.password_reset_requests(student_id)
  where status = 'pending';

-- ──────────────────────────────────────────────────────────
-- 3. Auto-update triggers
-- ──────────────────────────────────────────────────────────
create or replace function public.set_current_timestamp_updated_at()
returns trigger language plpgsql as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create or replace function public.get_server_now()
returns timestamptz language sql stable as $$
  select now();
$$;

grant execute on function public.get_server_now() to anon, authenticated;

create or replace function public.cancel_attendance_session(p_session_id text)
returns jsonb
language plpgsql
security invoker
set search_path = public
as $$
declare
  v_active_session_id text;
  v_deleted_count integer := 0;
begin
  if nullif(btrim(p_session_id), '') is null then
    raise exception 'session_id is required';
  end if;

  select value into v_active_session_id
    from public.system_settings
   where key = 'active_session_id'
   for update;

  if coalesce(v_active_session_id, '') <> p_session_id then
    raise exception 'The session is no longer active';
  end if;

  delete from public.attendance_logs where session_id = p_session_id;
  get diagnostics v_deleted_count = row_count;

  update public.system_settings set value = ''
   where key in ('pin', 'pin_expiry', 'current_grade', 'session_start', 'active_session_id');

  return jsonb_build_object('session_id', p_session_id, 'deleted_count', v_deleted_count);
end;
$$;

create or replace function public.bulk_set_attendance(
  p_student_ids text[],
  p_dates date[],
  p_status text,
  p_points integer default null
)
returns jsonb
language plpgsql
security invoker
set search_path = public
as $$
declare
  v_student_id text;
  v_date date;
  v_student_count integer;
  v_date_count integer;
  v_existing_count integer;
  v_inserted_count integer := 0;
  v_updated_count integer := 0;
  v_duplicate_count integer := 0;
  v_new_points integer;
begin
  if p_status not in ('มา', 'ขาด', 'ลา', 'กิจกรรม') then
    raise exception 'Invalid attendance status';
  end if;
  if p_status <> 'มา' and p_points is not null then
    raise exception 'Points can only be specified for present attendance';
  end if;
  if p_points is not null and p_points not in (0, 3, 5) then
    raise exception 'Points must be 0, 3, 5, or null';
  end if;

  select count(distinct student_id) into v_student_count
    from unnest(coalesce(p_student_ids, array[]::text[])) as ids(student_id)
   where nullif(btrim(student_id), '') is not null;
  select count(distinct attendance_date) into v_date_count
    from unnest(coalesce(p_dates, array[]::date[])) as dates(attendance_date)
   where attendance_date is not null;

  if v_student_count = 0 or v_date_count = 0 then
    raise exception 'At least one student and one date are required';
  end if;
  if v_student_count * v_date_count > 5000 then
    raise exception 'A bulk edit cannot exceed 5000 student-date pairs';
  end if;
  if (
    select count(distinct s.id) from public.students s
     where s.id = any(p_student_ids) and s.role = 'STUDENT'
  ) <> v_student_count then
    raise exception 'One or more student IDs are invalid';
  end if;

  for v_student_id in
    select distinct btrim(student_id) from unnest(p_student_ids) as ids(student_id)
     where nullif(btrim(student_id), '') is not null order by 1
  loop
    for v_date in
      select distinct attendance_date from unnest(p_dates) as dates(attendance_date)
       where attendance_date is not null order by 1
    loop
      select count(*) into v_existing_count from public.attendance_logs
       where student_id = v_student_id
         and (timestamp at time zone 'Asia/Bangkok')::date = v_date;

      if v_existing_count > 0 then
        if p_status = 'มา' and p_points is null then
          update public.attendance_logs set status = 'มา'
           where student_id = v_student_id
             and (timestamp at time zone 'Asia/Bangkok')::date = v_date;
        else
          v_new_points := case when p_status = 'มา' then p_points else 0 end;
          update public.attendance_logs set status = p_status, points = v_new_points
           where student_id = v_student_id
             and (timestamp at time zone 'Asia/Bangkok')::date = v_date;
        end if;
        v_updated_count := v_updated_count + 1;
        v_duplicate_count := v_duplicate_count + greatest(v_existing_count - 1, 0);
      else
        v_new_points := case when p_status = 'มา' and p_points is not null then p_points else 0 end;
        insert into public.attendance_logs (timestamp, student_id, status, points, session_id)
        values (
          (v_date::timestamp + time '12:00') at time zone 'Asia/Bangkok',
          v_student_id,
          p_status,
          v_new_points,
          null
        );
        v_inserted_count := v_inserted_count + 1;
      end if;
    end loop;
  end loop;

  return jsonb_build_object(
    'student_count', v_student_count,
    'date_count', v_date_count,
    'inserted_count', v_inserted_count,
    'updated_count', v_updated_count,
    'duplicate_count', v_duplicate_count
  );
end;
$$;

grant execute on function public.cancel_attendance_session(text) to anon, authenticated;
grant execute on function public.bulk_set_attendance(text[], date[], text, integer) to anon, authenticated;

drop trigger if exists set_students_updated_at      on public.students;
create trigger set_students_updated_at
  before update on public.students
  for each row execute function public.set_current_timestamp_updated_at();

drop trigger if exists set_shop_items_updated_at    on public.shop_items;
create trigger set_shop_items_updated_at
  before update on public.shop_items
  for each row execute function public.set_current_timestamp_updated_at();

drop trigger if exists set_system_settings_updated_at on public.system_settings;
create trigger set_system_settings_updated_at
  before update on public.system_settings
  for each row execute function public.set_current_timestamp_updated_at();

-- ──────────────────────────────────────────────────────────
-- 4. Row Level Security (RLS)  — เปิด + policy แบบ public
--    (ระบบใช้ anon key ตรวจสอบสิทธิ์ใน app เอง)
-- ──────────────────────────────────────────────────────────
alter table public.students          enable row level security;
alter table public.attendance_logs   enable row level security;
alter table public.shop_items        enable row level security;
alter table public.redemption_logs   enable row level security;
alter table public.password_reset_requests enable row level security;
alter table public.system_settings   enable row level security;

-- students
drop policy if exists "students_public_all"          on public.students;
create policy "students_public_all" on public.students
  for all to public using (true) with check (true);

-- attendance_logs
drop policy if exists "attendance_logs_public_all"   on public.attendance_logs;
create policy "attendance_logs_public_all" on public.attendance_logs
  for all to public using (true) with check (true);

-- shop_items
drop policy if exists "shop_items_public_all"        on public.shop_items;
create policy "shop_items_public_all" on public.shop_items
  for all to public using (true) with check (true);

-- redemption_logs
drop policy if exists "redemption_logs_public_all"   on public.redemption_logs;
create policy "redemption_logs_public_all" on public.redemption_logs
  for all to public using (true) with check (true);

-- password_reset_requests
drop policy if exists "password_reset_requests_public_all" on public.password_reset_requests;
create policy "password_reset_requests_public_all" on public.password_reset_requests
  for all to public using (true) with check (true);

-- system_settings
drop policy if exists "system_settings_public_all"   on public.system_settings;
create policy "system_settings_public_all" on public.system_settings
  for all to public using (true) with check (true);

-- Enable live teacher notifications for new and updated shop orders.
do $realtime$
begin
  if not exists (
    select 1
    from pg_publication
    where pubname = 'supabase_realtime'
  ) then
    raise exception 'Supabase Realtime publication was not found';
  end if;

  if not exists (
    select 1
    from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'redemption_logs'
  ) then
    alter publication supabase_realtime add table public.redemption_logs;
  end if;
end
$realtime$;

-- ──────────────────────────────────────────────────────────
-- 5. Storage bucket
-- ──────────────────────────────────────────────────────────
insert into storage.buckets (id, name, public)
values ('mathquest-storage', 'mathquest-storage', true)
on conflict (id) do update set public = excluded.public;

drop policy if exists "mathquest_storage_public_read"   on storage.objects;
create policy "mathquest_storage_public_read" on storage.objects
  for select to public using (bucket_id = 'mathquest-storage');

drop policy if exists "mathquest_storage_public_insert" on storage.objects;
create policy "mathquest_storage_public_insert" on storage.objects
  for insert to public with check (bucket_id = 'mathquest-storage');

drop policy if exists "mathquest_storage_public_update" on storage.objects;
create policy "mathquest_storage_public_update" on storage.objects
  for update to public
  using (bucket_id = 'mathquest-storage') with check (bucket_id = 'mathquest-storage');

drop policy if exists "mathquest_storage_public_delete" on storage.objects;
create policy "mathquest_storage_public_delete" on storage.objects
  for delete to public using (bucket_id = 'mathquest-storage');

-- ──────────────────────────────────────────────────────────
-- 6. System settings seed
-- ──────────────────────────────────────────────────────────
insert into public.system_settings (key, value) values
  ('app_name',         'MATH Quest'),
  ('school_name',      'กุงแก้ววิทยาคาร'),
  ('accent_color',     '#ffd814'),
  ('logo_url',         ''),
  ('pin',              ''),
  ('pin_expiry',       ''),
  ('current_grade',    ''),
  ('session_start',    ''),
  ('active_session_id',''),
  ('teacher_lat',      ''),
  ('teacher_lon',      ''),
  ('teacher_accuracy', '')
on conflict (key) do nothing;

-- ──────────────────────────────────────────────────────────
-- 7. Shop items seed (จาก Excel)
-- ──────────────────────────────────────────────────────────
insert into public.shop_items (item_id, item_name, cost, description, image_url, is_active) values
  ('ITEM_1777287693380', 'ปากกา',              50, '', '', true),
  ('ITEM_1777287708960', 'ไม้บรรทัด',          60, '', '', true),
  ('ITEM_1777287733286', 'แต้มพิเศษ 1 คะแนน', 25, '', '', true)
on conflict (item_id) do nothing;

-- ──────────────────────────────────────────────────────────
-- 8. Students seed — ครบ 81 คน (จาก Excel MasterData)
--
--    คอลัมน์ : id | name | password | grade | role | photo_url
--
--    password = รหัสประจำตัวประชาชน (ใช้ login ครั้งแรก)
--    ครู (admin) ใช้รหัส 021044
-- ──────────────────────────────────────────────────────────
insert into public.students (id, name, password, grade, role, photo_url) values
  -- ── ครู ──────────────────────────────────────────────
  ('admin',  'นายปิยะวัตร ผิวศิริ',            '021044',         'TEACHER', 'TEACHER', ''),

  -- ── ม.2 ──────────────────────────────────────────────
  ('02297',  'เด็กชายกิตติกร เหล่าทองสิงห์',    '1399900462799',  'ม.2', 'STUDENT', ''),
  ('02298',  'เด็กชายกิตติศักดิ์ ภู่ถนนนอก',    '1399000098144',  'ม.2', 'STUDENT', ''),
  ('02299',  'เด็กชายจิรวัฒน์ โพธิ์จักร',        '1399400098834',  'ม.2', 'STUDENT', ''),
  ('02300',  'เด็กชายฉัตรชัย เหล่าวงโคตร',       '1380700003202',  'ม.2', 'STUDENT', ''),
  ('02301',  'เด็กชายชนาภัทร อันตโก',            '1437800000090',  'ม.2', 'STUDENT', ''),
  ('02302',  'เด็กชายชิณพัฒน์ นามมุลตรี',        '1399000097059',  'ม.2', 'STUDENT', ''),
  ('02303',  'เด็กชายณฐวัฒน์ ไชยษร',             '1399900476188',  'ม.2', 'STUDENT', ''),
  ('02304',  'เด็กชายธนากร คนรู้',               '1749800577876',  'ม.2', 'STUDENT', ''),
  ('02305',  'เด็กชายธวัฒน์นันท์ ธรรมวัตเจริญ',  '1103704848091',  'ม.2', 'STUDENT', ''),
  ('02306',  'เด็กชายธัญพิสิษฐ หอมหวล',          '1399900487830',  'ม.2', 'STUDENT', ''),
  ('02308',  'เด็กชายพิชาญเมธ บุญชัยแสน',        '1399900481343',  'ม.2', 'STUDENT', ''),
  ('02309',  'เด็กชายภาณุพงศ์ พันทอง',           '1399000099931',  'ม.2', 'STUDENT', ''),
  ('02310',  'เด็กชายภาณุพงศ์ เภาพาน',           '1427900009536',  'ม.2', 'STUDENT', ''),
  ('02311',  'เด็กชายวราเมธ โสดาทุม',             '1427900009773',  'ม.2', 'STUDENT', ''),
  ('02312',  'เด็กชายวีรพงษ์ สงสุวงษ์',          '1729900934387',  'ม.2', 'STUDENT', ''),
  ('02313',  'เด็กชายสิทธิศักดิ์ มั่นคง',         '1399900458155',  'ม.2', 'STUDENT', ''),
  ('02314',  'เด็กชายสุกฤต อุทธชัย',              '1120500147130',  'ม.2', 'STUDENT', ''),
  ('02315',  'เด็กชายอัครวินท์ หาญบุตร',          '1399900484296',  'ม.2', 'STUDENT', ''),
  ('02316',  'เด็กหญิงกัญญาณัฎฐ์ พรมถิ่น',       '1399900487040',  'ม.2', 'STUDENT', ''),
  ('02317',  'เด็กหญิงกานต์ธิดา วงค์ไชยา',        '1149910328991',  'ม.2', 'STUDENT', ''),
  ('02318',  'เด็กหญิงจิระปิยา อังคะฮาด',          '1103400273560',  'ม.2', 'STUDENT', ''),
  ('02319',  'เด็กหญิงญาภา ศักดิ์ขวา',            '1399900480614',  'ม.2', 'STUDENT', ''),
  ('02320',  'เด็กหญิงณัชกานต์ แก้วกึ่งกรม',      '1399000101242',  'ม.2', 'STUDENT', ''),
  ('02321',  'เด็กหญิงณัฐณิชา เสียงลอย',          '1427900008360',  'ม.2', 'STUDENT', ''),
  ('02322',  'เด็กหญิงณัฐนิชา จันดา',             '1860401363776',  'ม.2', 'STUDENT', ''),
  ('02323',  'เด็กหญิงปวันรัตน์ บงแก้ว',           '1427900007576',  'ม.2', 'STUDENT', ''),
  ('02324',  'เด็กหญิงพิมพ์นิภา สิทธิเดช',         '1399000096940',  'ม.2', 'STUDENT', ''),
  ('02325',  'เด็กหญิงพิมพ์ลภัส กองกุล',           '1399000100521',  'ม.2', 'STUDENT', ''),
  ('02327',  'เด็กหญิงวรินทร คำสิมมา',             '1419902847999',  'ม.2', 'STUDENT', ''),
  ('02328',  'เด็กหญิงศิรินภา อันทะนัย',           '1399000099108',  'ม.2', 'STUDENT', ''),
  ('02329',  'เด็กหญิงสิรามล คนรู้',               '1749800582080',  'ม.2', 'STUDENT', ''),
  ('02330',  'เด็กหญิงสุภาวิตา วิมุลกุล',           '1399900474959',  'ม.2', 'STUDENT', ''),
  ('02331',  'เด็กหญิงอัสมา ทองพุ่ม',              '1810401276008',  'ม.2', 'STUDENT', ''),
  ('02335',  'เด็กหญิงปภาวรินทร์ ผิวแดง',          '1399000097075',  'ม.2', 'STUDENT', ''),

  -- ── ม.5 ──────────────────────────────────────────────
  ('02125',  'นายกวินท์ อิงชัยภูมิ',               '1427900000172',  'ม.5', 'STUDENT', ''),
  ('02128',  'นายชัยวัฒน์ โกฎิศรี',                '1399400085783',  'ม.5', 'STUDENT', ''),
  ('02131',  'นายภานุวัฒน์ ภูมิภัค',               '1199901306563',  'ม.5', 'STUDENT', ''),
  ('02132',  'นายภูมิภัทร กระแสบัว',               '1399900382680',  'ม.5', 'STUDENT', ''),
  ('02134',  'นายยศวริศ มูลเสนา',                  '1399000076396',  'ม.5', 'STUDENT', ''),
  ('02135',  'นายยัณตการ ศรีทอง',                  '1390401141875',  'ม.5', 'STUDENT', ''),
  ('02136',  'นายยุทธพล ภูพวก',                    '1399000075284',  'ม.5', 'STUDENT', ''),
  ('02137',  'นายรักแผ่นดิน โสมะมี',               '1421200158223',  'ม.5', 'STUDENT', ''),
  ('02149',  'นายจิรวงศ์ กาวนอก',                  '1100704145577',  'ม.5', 'STUDENT', ''),
  ('02154',  'นายธนวินท์ ทองใส',                   '1399900384046',  'ม.5', 'STUDENT', ''),
  ('02158',  'นายภาณุวัฒน์ กรรณลา',               '1399000076744',  'ม.5', 'STUDENT', ''),
  ('02159',  'นายมานิต เบ็ญขุนทด',                 '1399900365793',  'ม.5', 'STUDENT', ''),
  ('02160',  'นายศตเนติ ศรีสุทัศน์',               '1421200157278',  'ม.5', 'STUDENT', ''),
  ('02162',  'นายอัษฎา ไกลวัลย์',                  '1399900383546',  'ม.5', 'STUDENT', ''),
  ('02163',  'นายอาชวิน หาญบุตร',                  '1421200158991',  'ม.5', 'STUDENT', ''),
  ('02225',  'นายธีรศักดิ์ ก้านสัญชัย',             '139001141832',   'ม.5', 'STUDENT', ''),
  ('02232',  'นายระพีพัฒน์ สาคุณ',                 '1139600549203',  'ม.5', 'STUDENT', ''),
  ('02143',  'นางสาวพริสร ตะติฉิม',                '1104301198234',  'ม.5', 'STUDENT', ''),
  ('02146',  'นางสาวสุภัสสรา โกมลศรี',             '13990000700037', 'ม.5', 'STUDENT', ''),
  ('02147',  'นางสาวอริศรา ดีสี',                   '1399000070274',  'ม.5', 'STUDENT', ''),
  ('02165',  'นางสาวกาญจน์มณี วิศรี',              '1399000070258',  'ม.5', 'STUDENT', ''),
  ('02167',  'นางสาวจันทกานต์ แรงฤทธิ์',           '1427900000377',  'ม.5', 'STUDENT', ''),
  ('02168',  'นางสาวจิตตาภา คุณสิงห์',             '1390401141972',  'ม.5', 'STUDENT', ''),
  ('02169',  'นางสาวณัทธมนกาญจน์ แพงอ่อน',        '1119902519528',  'ม.5', 'STUDENT', ''),
  ('02171',  'นางสาวปรียนันท์ อิสสระเจริญ',         '1421200157871',  'ม.5', 'STUDENT', ''),
  ('02173',  'นางสาวพิชญาภา โคฮาด',               '1399000074831',  'ม.5', 'STUDENT', ''),

  -- ── ม.6 ──────────────────────────────────────────────
  ('02074',  'นายณัฐภัทร พิมพ์สิม',               '1421200156026',  'ม.6', 'STUDENT', ''),
  ('02075',  'นายธนวัฒน์ สุดชะดา',                '1399900351482',  'ม.6', 'STUDENT', ''),
  ('02077',  'นายบวรวิทย์ ขวัญศรี',               '1399000067231',  'ม.6', 'STUDENT', ''),
  ('02079',  'นายภานุวิทย์ ป้านภูมิ',              '1419902602678',  'ม.6', 'STUDENT', ''),
  ('02083',  'นายศุภกรณ์ เสกวงษา',                '1421200154490',  'ม.6', 'STUDENT', ''),
  ('02085',  'นายศุภชัย เย็นประคอง',               '1399000066161',  'ม.6', 'STUDENT', ''),
  ('02287',  'นายวรพงษ์ พัดสมร',                  '1139100032210',  'ม.6', 'STUDENT', ''),
  ('02288',  'นายสราวุธ คำตะพันธ์',               '1119902421285',  'ม.6', 'STUDENT', ''),
  ('02289',  'นายศุกลวัฒน์ พรมชุม',               '1399900348104',  'ม.6', 'STUDENT', ''),
  ('02089',  'นางสาวณัฐฐาศิรา ซันแลนด์',           '1129800173223',  'ม.6', 'STUDENT', ''),
  ('02092',  'นางสาวธิดาภา เด่นขุนทศ',             '1319901211315',  'ม.6', 'STUDENT', ''),
  ('02093',  'นางสาวธิดารัตน์ แสนบุญรัตน์',         '1399400082181',  'ม.6', 'STUDENT', ''),
  ('02094',  'นางสาวนวรัตน์ แสนภักดี',             '1209601623163',  'ม.6', 'STUDENT', ''),
  ('02095',  'นางสาวนารีรัตน์ เห็มสีดา',            '1399000066048',  'ม.6', 'STUDENT', ''),
  ('02097',  'นางสาวปณิดา ดำกลาง',                '1399000065181',  'ม.6', 'STUDENT', ''),
  ('02098',  'นางสาววรกานต์ ขายม',                '1420901420608',  'ม.6', 'STUDENT', ''),
  ('02101',  'นางสาววิลาสินี ภูมิเขต',              '1104301115797',  'ม.6', 'STUDENT', ''),
  ('02104',  'นางสาวสุนันธิณีย์ ศรีนนท์',           '1348600064169',  'ม.6', 'STUDENT', ''),
  ('02121',  'นางสาวมุฑิตา สุขษาเกษ',              '1399000066714',  'ม.6', 'STUDENT', ''),
  ('02231',  'นางสาวจิตติมา สงสุวงษ์',             '1129902136688',  'ม.6', 'STUDENT', '')
on conflict (id) do update set
  name       = excluded.name,
  password   = excluded.password,
  grade      = excluded.grade,
  role       = excluded.role;

-- ──────────────────────────────────────────────────────────
-- ✅ เสร็จสิ้น — ตาราง / RLS / Storage / Seed ครบทั้งหมด
-- ──────────────────────────────────────────────────────────
